/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myname;

import com.google.gson.Gson;

import java.util.LinkedHashMap;
import java.util.Map;

public class App {
    public String getGreeting() {
        System.out.println( "Hello World!" );
        Map<String,String> name = new LinkedHashMap<>();

        name.put("name", "Ivan");
        name.put("surname", "Ivanov");

        Gson gson = new Gson();
        return gson.toJson(name);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
